---
title: "Competion"
author: "Omar Alnafie"
date: "3/18/2022"
output: html_document
---


```{r, warning = FALSE, echo = FALSE}
setwd("C:\\Users\\om444\\Downloads")
competition_data <- read.csv("competition-data.csv", header = TRUE, sep = "," )
library(caret)
library(lattice)
library(pls)
library(tidyverse)
library(elasticnet)
library(corrplot)
library(tidyverse)
library(caret)
library(modelr)
library(ggplot2)
library(dplyr)
```


```{r, warning=FALSE, echo=FALSE}
outcome_vectore <-  competition_data [ , 22]
```

```{r, warning=FALSE, echo=FALSE}
## (iv) Data Summary

summary(outcome_vectore)
```

```{r, Warning = FALSE, echo=FALSE}

## histogram/density plot
library(ggplot2)
ggplot( competition_data, aes(x= outcome,)) + geom_histogram()
print(outcome)

```


```{r, warning=FALSE, echo=FALSE}
predictors_only_competition_data <- dplyr::select(competition_data, -outcome)
df_predictors_only <- data.frame(predictors_only_competition_data) 
competition_data_preprocessing_fit <- preProcess(
  df_predictors_only, 
  method = c("BoxCox", "center", "scale"))
competition_data_preprocessing_fit

```



```{r, warning=FALSE, echo=FALSE}


transformed_predictors <- predict(
  competition_data_preprocessing_fit, df_predictors_only)


preprocessed_competition_data <- add_column(transformed_predictors, 
    outcome = competition_data$outcome)
head(preprocessed_competition_data)

```

```{r, warning=FALSE, echo=FALSE}
library(caTools)
split <- sample.split(competition_data, SplitRatio = 0.8)
comTrain <- subset(competition_data, split = "TRUE")
comTest  <- subset(competition_data, split = "FALSE")
```
